apiVersion: v1
kind: Pod
metadata:
  name: mypod-tolerations
spec:
  containers:
  - name: mycontainer
    image: nginx
  tolerations:
  - key: "disktype"
    operator: "Equal"
    value: "ssd"
    effect: "NoSchedule"