apiVersion: apps/v1
kind: Deployment
metadata:
  name: invalid-app-configuration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invalid-app-configuration
  template:
    metadata:
      labels:
        app: invalid-app-configuration
    spec:
      containers:
      - name: main
        image: akhanregistry.azurecr.io/crashdemo:v1
