apiVersion: apps/v1
kind: Deployment
metadata:
  name: insufficient-resource-limit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insufficient-resource-limit
  template:
    metadata:
      labels:
        app: insufficient-resource-limit
    spec:
      containers:
      - name: main
        image: busybox
        resources:
          limits:
            memory: "2Mi"
