apiVersion: apps/v1
kind: Deployment
metadata:
  name: failing-liveness-probe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: failing-liveness-probe
  template:
    metadata:
      labels:
        app: failing-liveness-probe
    spec:
      containers:
      - name: main
        image: nginx
        livenessProbe:
          httpGet:
            path: /nonexistentpath
            port: 80
