apiVersion: apps/v1
kind: Deployment
metadata:
  name: bad-command
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bad-command
  template:
    metadata:
      labels:
        app: bad-command
    spec:
      containers:
      - name: main
        image: akhan2017/kubernetes-quickstart
        command: ["bad-command"]
