apiVersion: apps/v1
kind: Deployment
metadata:
  name: invalid-mountpath
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invalid-mountpath
  template:
    metadata:
      labels:
        app: invalid-mountpath
    spec:
      containers:
      - name: main
        image: nginx
        volumeMounts:
        - name: config-volume
          mountPath: invalid-mount-path
      volumes:
      - name: config-volume
        configMap:
          name: existing-configmap
