apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-limit-exceeded
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-limit-exceeded
  template:
    metadata:
      labels:
        app: memory-limit-exceeded
    spec:
      containers:
      - name: memory-consumer
        image: busybox
        command: ["sh", "-c", "dd if=/dev/zero of=/dev/shm/test bs=1M count=1000 & sleep 99999"]
        resources:
          limits:
            memory: "100Mi"  
            cpu: "0.5"       