apiVersion: v1
kind: Pod
metadata:
  name: nginx-tolerated-linux
spec:
  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: IfNotPresent
  tolerations:
    - key: "disktype"  
      operator: "Equal"
      value: "ssd"
      effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: "kubernetes.io/os"  
                operator: In
                values:
                  - "linux"  

