## This pod tolerates a node with a disktype label set to ssd.
apiVersion: v1
kind: Pod
metadata:
  name: mypod-toleration5
spec:
  containers:
  - name: mycontainer
    image: nginx
  tolerations:
  - key: "disktype"
    operator: "Equal"
    value: "ssd"
    effect: "NoSchedule"